name: DevApp

services:
  devapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: devappimage
    container_name: DevApp
    volumes:
      - .:/home
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: checkin
      WATCHPACK_POLLING: true
    networks:
      internal:
        ipv4_address: 172.20.0.10

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./init/db:/docker-entrypoint-initdb.d/
      - ./init/mariadb/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: checkin
    networks:
      internal:
        ipv4_address: 172.20.0.11

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1